const TOTAL=15,TIME=60,KEY="kataGandaRunnerRanking";
const s={name:"",cls:"",avatar:"boy",score:0,coins:0,lives:3,combo:0,best:0,correct:0,answered:0,time:TIME,cat:"penuh",correctLane:0,locked:false,timer:null,paused:false,wrong:[],currentAnswers:[]};
const $=id=>document.getElementById(id);const screens={home:$("home"),start:$("start"),game:$("game"),result:$("result"),ranking:$("ranking"),review:$("review"),help:$("help")};
function show(n){Object.values(screens).forEach(x=>x.classList.remove("active"));screens[n].classList.add("active")}
document.querySelectorAll("[data-home]").forEach(b=>b.onclick=()=>{clearInterval(s.timer);$("pauseOverlay").classList.remove("active");show("home")});
$("goStart").onclick=()=>show("start");$("goRanking").onclick=()=>{renderRanking();show("ranking")};$("goHelp").onclick=()=>show("help");
document.querySelectorAll(".avatar").forEach(b=>b.onclick=()=>{document.querySelectorAll(".avatar").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");s.avatar=b.dataset.avatar});
$("startBtn").onclick=start;$("againBtn").onclick=()=>show("start");$("rankingBtn").onclick=()=>{renderRanking();show("ranking")};$("reviewBtn").onclick=()=>{renderReview();show("review")};$("reviewBack").onclick=()=>show("result");$("copyBtn").onclick=copy;$("clearRanking").onclick=()=>{if(confirm("Padam semua ranking?")){localStorage.removeItem(KEY);renderRanking()}};
$("pauseBtn").onclick=pause;$("continueBtn").onclick=resume;$("restartBtn").onclick=()=>{resume();start()};$("quitBtn").onclick=()=>{clearInterval(s.timer);$("pauseOverlay").classList.remove("active");show("home")};
document.querySelectorAll(".choices button").forEach(b=>b.onclick=()=>answer(+b.dataset.lane,b));
function start(){let n=$("name").value.trim(),c=$("className").value;if(!n||!c){$("error").textContent="Sila isi nama dan pilih kelas dahulu.";return}$("error").textContent="";Object.assign(s,{name:n,cls:c,score:0,coins:0,lives:3,combo:0,best:0,correct:0,answered:0,time:TIME,locked:false,paused:false,wrong:[]});let r=$("runner");r.className="runner "+s.avatar+" lane1";update();show("game");next();clearInterval(s.timer);s.timer=setInterval(tick,1000)}
function tick(){if(s.paused)return;s.time--;$("time").textContent=s.time;if(s.time<=0)end()}
function next(){if(s.answered>=TOTAL||s.lives<=0||s.time<=0){end();return}s.locked=false;s.cat=["penuh","separa","berentak"][s.answered%3];$("mission").textContent=CATEGORY_LABELS[s.cat];let correct=pick(QUESTION_BANK[s.cat]);let cats=["penuh","separa","berentak","bukan"].filter(x=>x!==s.cat);let w1=pick(QUESTION_BANK[pick(cats)]),w2=pick(QUESTION_BANK[pick(cats)]);while(w2===w1||w2===correct)w2=pick(QUESTION_BANK[pick(cats)]);let arr=shuffle([correct,w1,w2]);s.currentAnswers=arr;s.correctLane=arr.indexOf(correct);document.querySelectorAll(".choices button").forEach((b,i)=>{b.textContent=arr[i];b.disabled=false;b.className=""});$("count").textContent=`${s.answered+1} / ${TOTAL}`;$("bar").style.width=`${(s.answered/TOTAL)*100}%`;move(1)}
function answer(lane,b){if(s.locked||s.paused)return;s.locked=true;document.querySelectorAll(".choices button").forEach(x=>x.disabled=true);move(lane);if(lane===s.correctLane){b.classList.add("correct");s.correct++;s.combo++;s.best=Math.max(s.best,s.combo);s.score+=10+Math.min(s.combo*2,20);s.coins+=2+Math.floor(s.combo/3);feedback(s.combo>=5?"SUPER!":"BAGUS!");say(s.combo>=5?`Combo ×${s.combo}!`:"Hebat!")}else{b.classList.add("wrong");document.querySelectorAll(".choices button")[s.correctLane].classList.add("correct");s.wrong.push({mission:CATEGORY_LABELS[s.cat],chosen:s.currentAnswers[lane],correct:s.currentAnswers[s.correctLane]});s.lives--;s.combo=0;feedback("CUBA LAGI!");say("Tak apa!")}s.answered++;update();setTimeout(next,1000)}
function move(l){let r=$("runner");r.classList.remove("lane0","lane1","lane2");r.classList.add("lane"+l)}
function update(){$("score").textContent=s.score;$("coins").textContent=s.coins;$("lives").textContent=s.lives;$("time").textContent=s.time;$("combo").textContent=s.combo>1?`🔥 COMBO ×${s.combo}`:""}
function say(t){let b=$("bubble");b.textContent=t;b.classList.add("show");clearTimeout(b.t);b.t=setTimeout(()=>b.classList.remove("show"),850)}
function feedback(t){let f=$("feedback");f.textContent=t;f.classList.remove("show");void f.offsetWidth;f.classList.add("show")}
function pause(){if(!screens.game.classList.contains("active"))return;s.paused=true;$("pauseOverlay").classList.add("active")}
function resume(){s.paused=false;$("pauseOverlay").classList.remove("active")}
function end(){clearInterval(s.timer);s.paused=false;$("bar").style.width="100%";$("rName").textContent=s.name;$("rClass").textContent=s.cls;$("rScore").textContent=s.score;$("rCorrect").textContent=`${s.correct}/${TOTAL}`;$("rCoins").textContent=s.coins;$("rCombo").textContent=s.best;let ratio=s.correct/TOTAL,stars=ratio>=.9?5:ratio>=.75?4:ratio>=.6?3:ratio>=.4?2:1;$("stars").textContent="★".repeat(stars)+"☆".repeat(5-stars);$("message").textContent=stars===5?"Luar biasa! Kamu ialah Juara Kata Ganda!":stars>=3?"Bagus! Teruskan latihan.":"Usaha yang baik! Cuba lagi.";$("reviewBtn").style.display=s.wrong.length?"block":"none";saveRanking();show("result")}
function saveRanking(){let list=getRanking();list.push({name:s.name,cls:s.cls,score:s.score,correct:s.correct});list.sort((a,b)=>b.score-a.score||b.correct-a.correct);localStorage.setItem(KEY,JSON.stringify(list.slice(0,10)))}
function getRanking(){try{return JSON.parse(localStorage.getItem(KEY)||"[]")}catch{return[]}}
function renderRanking(){let list=getRanking(),box=$("rankingList");if(!list.length){box.innerHTML="<p>Belum ada rekod. Jadilah pemain pertama!</p>";return}box.innerHTML=list.map((r,i)=>`<div class="rank-row ${i<3?"top"+(i+1):""}"><span>${i===0?"🥇":i===1?"🥈":i===2?"🥉":i+1}</span><span>${safe(r.name)} <small>· ${safe(r.cls)}</small></span><b>${r.score}</b></div>`).join("")}
function renderReview(){let box=$("reviewList");if(!s.wrong.length){box.innerHTML="<p>Hebat! Tiada jawapan salah.</p>";return}box.innerHTML=s.wrong.map((x,i)=>`<div class="review-item"><strong>Soalan ${i+1}: ${safe(x.mission)}</strong><p>Jawapan kamu: ${safe(x.chosen)}</p><p class="correct-answer">Jawapan betul: ${safe(x.correct)}</p></div>`).join("")}
function text(){return `KATA GANDA RUNNER TAHUN 3\nBM Cikgu Tan\nNama: ${s.name}\nKelas: ${s.cls}\nMarkah: ${s.score}\nBetul: ${s.correct}/${TOTAL}\nSyiling: ${s.coins}\nCombo Terbaik: ${s.best}`}
async function copy(){try{await navigator.clipboard.writeText(text());$("note").textContent="Markah telah disalin."}catch{prompt("Salin markah:",text())}}
function pick(a){return a[Math.floor(Math.random()*a.length)]}function shuffle(a){return [...a].sort(()=>Math.random()-.5)}function safe(v){return String(v).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]))}
