const $=x=>document.getElementById(x),screens=[...document.querySelectorAll('.screen')];
const BG=['court-front.jpg','field-block.jpg','garden-block.jpg','court-wide.jpg','covered-court.jpg'];
const qs=(t,a,c=0)=>({t,a,c});
const LEVELS=[
{name:'Pintu Sekolah',mode:'runner',label:'MISI 1 · RUNNER CHALLENGE',q:[qs('Cari kata ganda penuh.',['murid-murid','sekolah','berjalan']),qs('Cari kata ganda separa.',['jejari','rumah-rumah','cantik']),qs('Cari kata ganda berentak.',['sayur-mayur','buku-buku','membaca']),qs('Cari kata ganda penuh.',['guru-guru','tetikus','lauk-pauk']),qs('Cari kata ganda separa.',['dedaun','anak-anak','riuh-rendah']),qs('Cari kata ganda berentak.',['gunung-ganang','rumah','lelaki'])]},
{name:'Blok Ilmu',mode:'fill',label:'MISI 2 · ISI TEMPAT KOSONG',q:[qs('Ibu membeli ______ di pasar.',['sayur-mayur','jejari','rumah-rumah']),qs('______ sedang bermain di padang.',['Murid-murid','Tetikus','Lauk-pauk']),qs('Ayah menghidangkan pelbagai ______.',['lauk-pauk','pepohon','buku-buku']),qs('______ itu tumbuh subur di taman.',['Pepohon','Rerama','Saudara-mara']),qs('Kami menjemput ______ datang ke rumah.',['saudara-mara','dedaun','bola-bola']),qs('Rambut adik menjadi ______.',['kusut-masai','anak-anak','tetamu'])]},
{name:'Taman Bahasa',mode:'match',label:'MISI 3 · PADANKAN PERKATAAN',q:[{pairs:[['anak-anak','Kata Ganda Penuh'],['jejari','Kata Ganda Separa'],['lauk-pauk','Kata Ganda Berentak']]},{pairs:[['guru-guru','Kata Ganda Penuh'],['pepohon','Kata Ganda Separa'],['riuh-rendah','Kata Ganda Berentak']]},{pairs:[['bunga-bunga','Kata Ganda Penuh'],['rerama','Kata Ganda Separa'],['gunung-ganang','Kata Ganda Berentak']]}]},
{name:'Gelanggang Biru',mode:'basket',label:'MISI 4 · BASKET CHALLENGE',q:[qs('Bola “anak-anak” perlu masuk ke bakul yang betul.',['Kata Ganda Penuh','Kata Ganda Separa','Kata Ganda Berentak']),qs('Bola “jejari” perlu masuk ke bakul yang betul.',['Kata Ganda Separa','Kata Ganda Penuh','Kata Ganda Berentak']),qs('Bola “sayur-mayur” perlu masuk ke bakul yang betul.',['Kata Ganda Berentak','Kata Ganda Penuh','Kata Ganda Separa']),qs('Bola “guru-guru” perlu masuk ke bakul yang betul.',['Kata Ganda Penuh','Kata Ganda Separa','Kata Ganda Berentak']),qs('Bola “rerama” perlu masuk ke bakul yang betul.',['Kata Ganda Separa','Kata Ganda Penuh','Kata Ganda Berentak'])]},
{name:'Dewan Juara',mode:'boss',label:'BOSS TERAKHIR · CABARAN CAMPURAN',q:[qs('Pilih ayat yang paling tepat.',['Ibu membeli sayur-mayur di pasar.','Ibu membeli jejari di pasar.','Ibu membeli rumah-rumah di pasar.']),qs('Yang manakah kata ganda separa?',['pepohon','buku-buku','warna-warni']),qs('Yang manakah kata ganda berentak?',['riuh-rendah','murid-murid','tetikus']),qs('Lengkapkan: ______ berkumpul di dewan.',['Murid-murid','Dedaun','Lauk-pauk']),qs('Yang manakah BUKAN kata ganda?',['berjalan','anak-anak','rerama']),qs('Lengkapkan: Rambutnya ______.',['kusut-masai','guru-guru','pepohon'])]}
];
let s={name:'',cls:'',av:'boy',unlock:0,stars:[0,0,0,0,0],coins:0,bgm:true,lev:0,i:0,score:0,life:3,correct:0,wrong:[],paused:false},ctx=null,music=null;
function show(id){screens.forEach(x=>x.classList.remove('active'));$(id).classList.add('active')}
function save(){localStorage.setItem('bahauSave',JSON.stringify(s))}function load(){try{Object.assign(s,JSON.parse(localStorage.getItem('bahauSave')||'{}'))}catch{}}
function tone(f,d=.12,v=.04){if(!s.bgm)return;if(!ctx)ctx=new(window.AudioContext||window.webkitAudioContext)();let o=ctx.createOscillator(),g=ctx.createGain();o.type='triangle';o.frequency.value=f;g.gain.value=v;o.connect(g);g.connect(ctx.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+d);o.stop(ctx.currentTime+d)}
function startMusic(){if(!s.bgm)return;stopMusic();let n=[262,330,392,523,392,330],i=0;music=setInterval(()=>tone(n[i++%n.length],.15,.025),360)}function stopMusic(){clearInterval(music)}
function map(){show('map');$('who').textContent=s.name+' · '+s.cls;$('money').textContent=s.coins;$('stars').textContent=s.stars.reduce((a,b)=>a+b,0);$('nodes').innerHTML=LEVELS.map((l,i)=>`<button class="node ${i>s.unlock?'lock':''} ${s.stars[i]?'done':''}" data-i="${i}"><b>${i<4?i+1:'👑'} · ${l.name}</b><small>${s.stars[i]?'⭐'.repeat(s.stars[i]):l.label}</small></button>`).join('');document.querySelectorAll('.node').forEach(b=>b.onclick=()=>{let i=+b.dataset.i;if(i<=s.unlock)start(i)})}
function start(i){Object.assign(s,{lev:i,i:0,score:0,life:3,correct:0,wrong:[],paused:false});$('scene').style.backgroundImage=`url('assets/bg/${BG[i]}')`;$('label').textContent=LEVELS[i].label;hud();show('game');render();startMusic()}
function hud(){$('life').textContent=s.life;$('score').textContent=s.score;$('coin').textContent=s.coins}
function render(){let l=LEVELS[s.lev];if(s.life<=0||s.i>=l.q.length)return finish();$('prog').textContent=`${s.i+1}/${l.q.length}`;if(l.mode==='match')return match(l.q[s.i]);let item=l.q[s.i];$('q').textContent=item.t;let arr=item.a.map((x,i)=>({x,i})).sort(()=>Math.random()-.5),wrap=document.createElement('div');wrap.className=l.mode==='basket'?'basket':'answers';$('area').innerHTML='';arr.forEach(z=>{let b=document.createElement('button');b.className='ans';b.textContent=z.x;b.onclick=()=>answer(z.i,b,item);wrap.appendChild(b)});$('area').appendChild(wrap)}
function answer(i,b,item){if(s.paused)return;document.querySelectorAll('#area button').forEach(x=>x.disabled=true);if(i===item.c){b.classList.add('correct');s.score+=100;s.coins+=5;s.correct++;flash('BAGUS!',700)}else{b.classList.add('wrong');s.life--;s.wrong.push({q:item.t,y:item.a[i],a:item.a[item.c]});flash('CUBA LAGI!',220)}s.i++;hud();setTimeout(render,850)}
function match(item){$('q').textContent='Padankan perkataan dengan jenis kata ganda yang betul.';$('area').innerHTML='';let selected=null,done=0,left=item.pairs.map((p,i)=>({x:p[0],i})).sort(()=>Math.random()-.5),right=item.pairs.map((p,i)=>({x:p[1],i})).sort(()=>Math.random()-.5),w=document.createElement('div');w.className='matchgrid';let a=document.createElement('div'),b=document.createElement('div');a.className=b.className='matchcol';left.forEach(z=>{let x=document.createElement('button');x.className='match';x.textContent=z.x;x.onclick=()=>{document.querySelectorAll('.matchcol:first-child .match').forEach(k=>k.classList.remove('selected'));x.classList.add('selected');selected=z.i};a.appendChild(x)});right.forEach(z=>{let x=document.createElement('button');x.className='match';x.textContent=z.x;x.onclick=()=>{if(selected===null)return;if(selected===z.i){x.classList.add('correct');document.querySelector('.selected')?.classList.add('correct');document.querySelector('.selected')?.classList.remove('selected');selected=null;done++;s.score+=80;s.coins+=3;flash('PADANAN BETUL!',700);if(done===item.pairs.length){s.correct++;s.i++;setTimeout(render,800)}}else{s.life--;s.wrong.push({q:'Padankan '+item.pairs[selected][0],y:z.x,a:item.pairs[selected][1]});document.querySelector('.selected')?.classList.remove('selected');selected=null;hud();flash('BELUM TEPAT!',220);if(s.life<=0)setTimeout(finish,700)}};b.appendChild(x)});w.append(a,b);$('area').appendChild(w)}
function flash(t,f){$('feed').textContent=t;$('feed').classList.remove('show');void $('feed').offsetWidth;$('feed').classList.add('show');tone(f)}
function finish(){stopMusic();let total=LEVELS[s.lev].q.length,r=s.correct/total,st=r>=.8?3:r>=.5?2:1;s.stars[s.lev]=Math.max(s.stars[s.lev],st);s.unlock=Math.max(s.unlock,Math.min(4,s.lev+1));save();rankSave();$('doneTitle').textContent=s.lev===4?'Wira Kata Ganda!':'Misi Selesai!';$('doneText').textContent=LEVELS[s.lev].name+' berjaya diselesaikan.';$('dscore').textContent=s.score;$('dcorr').textContent=s.correct+'/'+total;$('dstars').textContent='⭐'.repeat(st);$('dcoin').textContent=s.coins;$('review').style.display=s.wrong.length?'block':'none';show('done')}
function review(){$('reviewList').innerHTML=s.wrong.map((x,i)=>`<div class="reviewitem"><b>${i+1}. ${x.q}</b><p>Jawapan kamu: ${x.y}</p><p><strong>Jawapan betul: ${x.a}</strong></p></div>`).join('')}
function rankSave(){let a=[];try{a=JSON.parse(localStorage.getItem('bahauRank')||'[]')}catch{}a.push({n:s.name,c:s.cls,st:s.stars.reduce((x,y)=>x+y,0),co:s.coins});a.sort((x,y)=>y.st-x.st||y.co-x.co);localStorage.setItem('bahauRank',JSON.stringify(a.slice(0,10)))}
function ranking(){let a=[];try{a=JSON.parse(localStorage.getItem('bahauRank')||'[]')}catch{}$('rankList').innerHTML=a.length?a.map((x,i)=>`<div class="rankrow"><span>${i<3?['🥇','🥈','🥉'][i]:i+1}</span><span>${x.n} · ${x.c}</span><b>${x.st}⭐</b></div>`).join(''):'<p>Belum ada rekod.</p>';show('ranking')}
$('new').onclick=()=>show('profile');$('cont').onclick=()=>{load();s.name?map():show('profile')};$('rank').onclick=ranking;$('enter').onclick=()=>{let n=$('name').value.trim(),c=$('cls').value;if(!n||!c)return $('err').textContent='Sila isi nama dan pilih kelas.';Object.assign(s,{name:n,cls:c,unlock:0,stars:[0,0,0,0,0],coins:0});save();map()};document.querySelectorAll('.av').forEach(b=>b.onclick=()=>{document.querySelectorAll('.av').forEach(x=>x.classList.remove('sel'));b.classList.add('sel');s.av=b.dataset.av});document.querySelectorAll('.home').forEach(b=>b.onclick=()=>{stopMusic();show('home')});document.querySelectorAll('.tomap').forEach(b=>b.onclick=()=>{stopMusic();$('overlay').classList.remove('show');map()});$('pause').onclick=()=>{$('overlay').classList.add('show');s.paused=true};$('resume').onclick=()=>{$('overlay').classList.remove('show');s.paused=false};$('restart').onclick=()=>{$('overlay').classList.remove('show');start(s.lev)};$('next').onclick=()=>map();$('review').onclick=()=>{review();show('reviewPage')};$('backDone').onclick=()=>show('done');$('bgm').onclick=()=>{s.bgm=!s.bgm;$('bgm').textContent=s.bgm?'🔊 BGM: ON':'🔇 BGM: OFF';s.bgm?startMusic():stopMusic();save()};load();$('bgm').textContent=s.bgm?'🔊 BGM: ON':'🔇 BGM: OFF';
